apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps
  namespace: argocd
spec:
  project: argocd-apps
  source:
    path: clusters/foxbat/argocd-apps
    repoURL: "https://github.com/fulcrum29/foxbat"
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      enabled: true
      selfHeal: true
