apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd-apps
spec:
  sourceRepos:
    - "*"
  destinations:
    - namespace: "argocd"
      server: "https://kubernetes.default.svc"
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
